[package]
name = "opcua-server-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opcua = { version = "0.10", features = ["console-logging", "server"] }
clap = { version = "4.0", features = ["derive", "string"] }
rusqlite="0.32.1"
time="~0.1.44"
openssl-sys="~0.9.72"
libc="~0.2.112"
tokio-macros="~1.7.0"
tokio="~1.15.0"
tokio-util="~0.6.9"
